POST http://localhost:3000/api/users/sign-up
Content-Type: application/json

{    
    "email": "carlosdolzm@gmail.com",
    "password": "123456",
    "name": "Carlos",
    "surname": "Dolz Martín",
    "birthDate": "12-Septiembre-1994"
}

###

POST http://localhost:3000/api/users/login
Content-Type: application/json

{        
    "email": "carlosdolzm@gmail.com",
    "password": "123456"
}